### ISSUE TITLE
Right Scroll Bar is not appearing or missing in HR Dashboard 11.0 (Odoo 11)

### ISSUE THREAD

**Issue by Faraz76** [hilarak/odoo_community_addons#1]
Dear Hilarak,

Today i have installed your HR Dashboard Module...its a excellent work and off course lot of hard work and efforts has been contributed by you.

As i am testing this module, i found that scroll bar is not appearing at HR Dashboard Module. see attached screen short).

I have tested it with different browsers such as IE, Chrome, Firefox.

![dashboard screen short](https://user-images.githubusercontent.com/16869724/37232166-df70bb4c-23fe-11e8-89bc-0e6eaf52625c.jpg)

**Comment by hilarak** [comment]
Scroll bar is actually disabled, and I will improve much more css in next version. You can explicitly give scroll bar as 
`overflow: scroll;`

**Comment by prakashjain** [comment]
Odoo 12 hr_dashboard installed.
https://screenshots.firefox.com/sCEWXEPxO0fQd2pr/localhost
Extra space in right side (20 to 30 %) due to space Y-axis scroll not visible, 
after scroll x-axis to end then only visible. Is any way to remove extra space in right side. 
Thanks
