### ISSUE TITLE
Site crushed when I disable "Autofooter"

### ISSUE THREAD

**Issue by KomarovAlea** [hilarak/odoo_community_addons#13]
https://github.com/hilarak/odoo_community_addons/blob/8b79681cf9358e745608c87dc682f0f45cca41da/odoo-debrand-11/views/views.xml#L153

By default in Odoo activated "Autofooter". When I disable it, my site is crushed and I get error.

**Comment by DanielMaimba** [comment]
I also experienced this same issue, has there been any progress on this?

**Comment by KomarovAlea** [comment]
You can fixing it, if disable template with id "footer_extend".
Or even remove this template 
```
    <template id="footer_extend" inherit_id="website.footer_custom">
        <xpath position="replace" expr="//h2"/>
    </template>
```
in file /odoo-debrand-11/views/views.xml
and reinstall this module in Odoo
