### ISSUE TITLE
Odoo-Debranding 11

### ISSUE THREAD

**Issue by walidkhmah** [hilarak/odoo_community_addons#15]
When I tried to install this module in windows 10 platform, odoo 11 and  python 3.6 environment I got the following error 500 

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: web.layout
Path: /templates/t/html/head/t[2]/link
Node: <link type="image/x-icon" rel="shortcut icon" t-att-href="'data:image/png;base64,%s' % to_text(website_id and website_id[0] and website_id[0].favicon or '')"/>
2018-09-12 07:01:37,169 15012 INFO Install_Test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [239]
2018-09-12 07:01:39,403 15012 INFO Install_Test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [244]
2018-09-12 07:01:40,476 15012 ERROR Install_Test odoo.addons.website.models.ir_http: 500 Internal Server Error:

**Comment by yanfrank** [comment]
Hi Dev Team, you do a EXCELLENT work with Odoo Debrand module, its very usefull.
Im user of Material/United Backend Theme module too. 
I have issues with company_logo after install your module.

To reproduce:
I use Odoo11, ubuntu 16, 
First, i install https://www.odoo.com/apps/themes/11.0/backend_theme_v11/
Second, i setup the company logo, save, refresh and i see my logo on APPs. 1.png
![imagen](https://user-images.githubusercontent.com/22683525/50409070-9e721200-07bd-11e9-8400-024d7397fc37.png)

Thirth, install your module and company_logo is replaced. 2.png
![imagen](https://user-images.githubusercontent.com/22683525/50409081-afbb1e80-07bd-11e9-8141-daa4c0c06c36.png)

That is the issue, company_logo is replaced, if i uninstall Odoo Debrand module, logo is working good.

Thank you for your time.

**Comment by hilarak** [comment]
Goto debrand settings and set company logo.
