### ISSUE TITLE
HR Dashboard Module print pdf

### ISSUE THREAD

**Issue by mokerosan** [hilarak/odoo_community_addons#16]
when he tried to print in PDF he sent me the following error.
how do I solve it? thanks!

`Uncaught Malformed table row, a cell is undefined.`
```
http://10.149.148.146:8069/web/content/655-0b2e212/web.assets_backend.js:3164
Rastreo de error:
undefined
```
[https://ibb.co/jM28w9](url)

**Comment by hilarak** [comment]
have you done any changes to the table?

**Comment by hilarak** [comment]
@mokerosan can you print other pdf reports in odoo, I have found an issue you raised on odoo. Update to correct wkhtmltopdf version
