### ISSUE TITLE
Dependency on LiveChat

### ISSUE THREAD

**Issue by ghost** [hilarak/odoo_community_addons#2]
Thanks for that great plugin! But is there some way to use it without turn on livechat? I do not have a livechat on my page and turning it on just because debranding is not so nice. When i try to uninstall livechat it also says it is going to uninstall debranding :/

**Comment by hilarak** [comment]
odoo-debrand-11 is depended on im_live_chat, that's why uninstall wizard shows debrand addon while uninstalling live chat. To remove the dependency you have to remove the code from im live chat and remove the addon from dependency list.
