### ISSUE TITLE
Serialization error 

### ISSUE THREAD

**Issue by lukvml** [hilarak/odoo_community_addons#20]
Impacted versions: 12.0e

Current behavior: creates double entries everywhere (SO,PO,Timesheets)

Error postgres
odoo@AIT ERROR: could not serialize access due to concurrent update
odoo@AIT STATEMENT: UPDATE "bus_presence" SET "last_poll"='2019-01-20 20:32:49' WHERE id IN (1)

Error odoo:
odoo.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.8038 sec...

**Comment by prakashjain** [comment]
Facing similar  server issue every time Try to reconnect  odoo application. @lukvml Is any extra other customize  done in odoo-debrand module? Odoo 12 downloaded from git or nightly builds?

**Comment by hilarak** [comment]
Can you please give me the details to reproduce the same

**Comment by prakashjain** [comment]
After installing De-branding module, please create new employee or user record and list view search the created record, same record entry will showing 2 times.
De-branding module JS related code removed after that issue fixed. Please let me know to keep js code feature and double entry issue fix .

**Comment by hilarak** [comment]
Thanks, @prakashjain @lukvml, I will check and the test the addon. Will reach you soon.

**Comment by hilarak** [comment]
Fix related duplicating records is done.

**Comment by prakashjain** [comment]
Thanks @hilarak will check. Please let me know De-branding without depends "Website" module is available ?
