### ISSUE TITLE
Triple duplicate of settings

### ISSUE THREAD

**Issue by Industruino** [hilarak/odoo_community_addons#21]
Dear Hilar,

First of all, thank you for releasing this module!

After installing the Debrand Odoo module I'm seeing three duplicate tabs in the settings. This might be 
because I have multiple companies set up in Odoo, but it doesn't allow me to change the settings individually. When I write any value into one box it gets duplicated in the other two tabs automatically. It also doesn't identify these tabs with separate names.

I do have to note that I first installed the module via the Odoo interface (upload .zip in the Apps menu), which resulted in a failed install, with the general settings menu broken as result as well. I then did a manual install, which fixed the general settings menu again and made your module work. (issue described in separate Issue).

(I've noticed a couple of other issues, which might be related but I will submit separate issue for that for clarity sake). 

Thank you in advance.

Kind Regards,
Loic

<img width="964" alt="Screenshot 2019-03-26 at 17 00 41" src="https://user-images.githubusercontent.com/4273528/54983964-c81f1d00-4fe8-11e9-9cce-9769ce39c097.png">

**Comment by hilarak** [comment]
Thanks, for reporting me, I will check for a multi-company environment

**Comment by Industruino** [comment]
@hilarak ,some extra info that might help you debug: Apart from multi-company, I have multi-website enabled (3 websites linked to 3 companies). So the issue might also be related to multi-website.

**Comment by hilarak** [comment]
@Industruino any other issue while using my module on multi-website?

**Comment by Industruino** [comment]
@hilarak no other issues so far, all is good.
