### ISSUE TITLE
Name of page not shown with name of site

### ISSUE THREAD

**Issue by Industruino** [hilarak/odoo_community_addons#23]
When applying the Odoo Debrand module and choosing a company in the Debrand settings, the company name is shown, but without the unique page name. 

For example, when visiting the Blog, originally the top of the page would display "Blog Posts | Company name", after applying the Debrand module it only show "Company name". Is it please possible to restore individual page names?

**Comment by hilarak** [comment]
@Industruino I will check the issue and do the updates.

**Comment by Industruino** [comment]
@hilarak Thanks Hilar!

**Comment by hilarak** [comment]
@Industruino 342976a7767abfddd29c793c0fd038f3dbbb52d8

**Comment by Industruino** [comment]
@hilarak The update works, but at the end of the title a "NULL"  string is displayed. I assume this is probably due to the multi-website setup.

**Comment by hilarak** [comment]
debranding cannot be done for a multi-website, need more to do for that setup I think. Anyway, there is a new commit to fix a bug. @Industruino  related to the page title. For the multi-website will do after collecting some more info.
