### ISSUE TITLE
[11] Debrand module resets company logo to default

### ISSUE THREAD

**Issue by Ark74** [hilarak/odoo_community_addons#24]
On Odoo 11 I've seen that when installing the module the default odoo logo is used when calling 

`<img src="/web/binary/company_logo">`

 replacing the custom company logo.

This affects the POS ticket logo and other places.

When removing the module, the custom company logo is set back again.

Here an example of the issue:
![debrand](https://user-images.githubusercontent.com/7444518/58416386-ff409780-8046-11e9-8456-82ab4ed2add6.gif)

**Comment by hilarak** [comment]
If I correctly understand u, then you have to clear image cache of the browser.

**Comment by Ark74** [comment]
I did, several times. That's the reason I filled this issue.
I'll try again. Thanks.

**Update**: Seems browser cache was the case. Weird.
Thanks!
