### ISSUE TITLE
TRANSLATE

### ISSUE THREAD

**Issue by Pereiral01** [hilarak/odoo_community_addons#4]
Hello, I installed this GREAT module, but I would like to translate it with *.po file ... I saw it hasn't i18n Directory, so Where I can hold my *.po file to translate it, please?
Many thanks

**Comment by hilarak** [comment]
Good to hear, you please specify which addon and you can create an i18n directory inside the addon hierarchy.

**Comment by hilarak** [comment]
@Pereiral01 translation folder added
