### ISSUE TITLE
Odoo Menu Items (my odoo.com account, etc) not going away

### ISSUE THREAD

**Issue by ashishcompwiz** [hilarak/odoo_community_addons#7]
Please see this screenshot
![image](https://user-images.githubusercontent.com/32674479/42418384-2f0c3f2e-82bd-11e8-936d-7e3f629d12e2.png)

You can see that odoo Menu Items (my odoo.com account, etc) not going away
using odoo 11

**Comment by hilarak** [comment]
Have you got any error log while installing? @ashishcompwiz

**Comment by ashishcompwiz** [comment]
hi 
i restarted the python server and the menu items were gone.
Sorry for inconvience. i have been having numerous problems due to odoo not refreshing assets.
Is there a command for that to refresh odoo assets?

**Comment by hilarak** [comment]
try to upgrade the base using the following command.
make cmd pointer to odoo dir
`sudo su postgres`
password:
`./odoo-bin -u base -d db_name`
